[package]
name = "palindrome"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
termion = "4.0.3"
ctrlc = "3.2.3"
shamir = "2.0.0"
